### ISSUE TITLE
OPTIONS request type for CORS

### ISSUE THREAD

**Issue by lucacastelnuovo** [miladrahimi/phprouter#25]
Could you add `$router->options('/', 'ExampleClass@options');` support?

CORS sends an Pre-Flight request using the `OPTIONS` HTTP method.
The only way to catch this currently is using the `$router->any()` method.

But this removes the ability to create an RESTful endpoint. 
Because I can no longer create seperate routes for GET,POST,PUT,PATCH and DELETE.

**Comment by miladrahimi** [comment]
Hi,I’m consider this for the next version, but for now you can use $router->map(‘option’, ‘/‘, controller)Thanks for your suggestion.Bests,Milad Rahimi---milad93x@gmail.cominfo@miladrahimi.comhttps://miladrahimi.com---- On Wed, 20 May 2020 14:54:53 +0430  notifications@github.com<notifications@github.com> wrote ---- 
Could you add $router->options('/', 'ExampleClass@options'); support? 
CORS sends an Pre-Flight request using the OPTIONS HTTP method. 
The only way to catch this currently is using the $router->any() method. 
But this removes the ability to create an RESTful endpoint. 
Because I can no longer create seperate routes for GET,POST,PUT,PATCH and DELETE.

**Comment by lucacastelnuovo** [comment]
Great, I will use `$router->map(‘option’, ‘/‘, controller)`

**Comment by miladrahimi** [comment]
of course, you probably need to use uppercase from of it ('OPTIONS') as mentioned here:
https://github.com/miladrahimi/phprouter#http-methods
