### ISSUE TITLE
Container: Reflection failed

### ISSUE THREAD

**Issue by lucacastelnuovo** [miladrahimi/phprouter#33]
When trying to get container it fails with an reflection error
```php
$this->router->getContainer()->singleton(\CQ\Config\Config::class, \CQ\Config\Config::class);

$this->container->has(\CQ\Config\Config::class); // Returns true
$this->container->get(\CQ\Config\Config::class); // Returns Reflection failed for CQ\Config\Config
```

**Comment by miladrahimi** [comment]
I couldn't find the `\CQ\Config\Config::class` on the internet.
Did you test the container for other classes?
Isn't that `Config::class` an abstract class?

**Comment by lucacastelnuovo** [comment]
Hi sorry for the late reply.
The class is here: https://github.com/CubeQuence/framework/blob/update/php8/src/CubeQuence/Config/Config.php

**Comment by miladrahimi** [comment]
The problem might be the constructor parameter of your config class:

```php
namespace CQ\Config;

use CQ\Helpers\Arr;

class Config
{
    private $dir;

    /**
     * Define project dir.
     *
     * @param string $dir
     */
    public function __construct($dir)
```

Since it has constructor parameter, you should handle it using one these ways:
1. resolve the parameter inside a closure and bind the closure:
```php
$container->singleton(Config::class, function() { return new Config('path/to/...'); }
```
2. or bind the parameter value to the container (via name binding (start the id with `$`))
```php
$container->singleton('$dir', 'path/to/...');
$container->get(Config::class);
```

Another tip:
You don't need to bind implementation classes like yours:
```php
$this->router->getContainer()->singleton(\CQ\Config\Config::class, \CQ\Config\Config::class);
```
The container can find the class without, but interfaces must be binded explicitly.

By the way, you should read  https://github.com/miladrahimi/phpcontainer
